# Generated by Django 3.1.3 on 2025-04-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20250315_1744'),
        ('pybo', '0005_comment'),
        ('pybo', '0005_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
    ]
